FROM opensuse/leap:15.6

ENV PYTHONUNBUFFERED=1
ENV INTERVAL=1d

RUN zypper --non-interactive update && \
    zypper --non-interactive install \
    desktop-file-utils \
    python3 \
    make \
    rpm-build \
    rpmdevtools \
    binutils \
    #gtk-update-icon-cache \
    util-linux \
    && zypper --non-interactive clean

WORKDIR /build

COPY scripts/* .
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /build/start.sh /entrypoint.sh

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/build/start.sh"]