server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name _;

    root /data;

    #auth_basic "Restricted Access to the Repository";
    #auth_basic_user_file /etc/nginx/.htpasswd;

    location = /gpg {
        auth_basic off;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
        empty_gif;
    }
    
    location / {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        

        location ~* \.(xml|xml\.gz|xml\.bz2|sqlite|sqlite\.bz2|sqlite\.gz)$ {
            expires -1;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }

    location ~ \.rpm$ {
        sendfile on;
        tcp_nopush on;
        expires 30d;
        add_header Cache-Control "public";
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    access_log /logs/repo_access.log main;
    error_log /logs/repo_error.log warn;
}